import { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { apiFetch } from '../../../core/api/client';

export default function ForgotPasswordScreen() {
  const [email,setEmail]=useState(''); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState(''); const [error,setError]=useState(''); const [resetToken,setResetToken]=useState('');
  async function submit(){
    setBusy(true);setError('');setNotice('');
    try {const response=await apiFetch('/auth/forgot-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const body=await response.json();if(!response.ok)throw new Error(body?.error?.message||'Request nahi ho saki.');setNotice(body.data.message);setResetToken(body.data.development_reset_token||'');}
    catch(reason){setError(reason instanceof Error?reason.message:'API connection nahi ho saka.')}finally{setBusy(false)}
  }
  return <View style={styles.screen}><Text style={styles.brand}>ProofLens <Text style={styles.ai}>AI</Text></Text><Text style={styles.kicker}>ACCOUNT SECURITY</Text><Text style={styles.title}>Reset your password</Text><Text style={styles.copy}>Agar account maujood hai aur email setup hai to reset link bhej diya jayega.</Text><View style={styles.feature}><Text style={styles.featureTag}>PROOFLENS AI · ACCOUNT SAFETY</Text><Text style={styles.featureTitle}>A safer next step starts with a check.</Text><Text style={styles.featureCopy}>ProofLens helps you inspect suspicious links, messages, QR codes and files.</Text></View><TextInput style={styles.input} placeholder="Email address" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address"/>{error!==''&&<Text style={styles.error}>{error}</Text>}{notice!==''&&<Text style={styles.notice}>{notice}</Text>}{resetToken!==''&&<Pressable style={styles.primary} onPress={()=>router.push({pathname:'/reset-password',params:{token:resetToken}})}><Text style={styles.primaryText}>Continue to set new password</Text></Pressable>}<Pressable style={styles.primary} onPress={submit} disabled={busy}>{busy?<ActivityIndicator color="white"/>:<Text style={styles.primaryText}>Send reset link</Text>}</Pressable><Pressable style={styles.back} onPress={()=>router.back()}><Text style={styles.backText}>‹ Back to sign in</Text></Pressable></View>;
}
const styles=StyleSheet.create({screen:{flex:1,justifyContent:'center',padding:24,backgroundColor:'#f7f9fa'},brand:{fontSize:22,fontWeight:'800',color:'#192b3d',marginBottom:34},ai:{fontSize:12,color:'#668492'},kicker:{fontSize:10,letterSpacing:1.4,color:'#8999a2',fontWeight:'700'},title:{fontSize:25,fontWeight:'700',color:'#192b3d',marginTop:8},copy:{fontSize:12,lineHeight:19,color:'#7b8a93',marginTop:7,marginBottom:10},feature:{padding:14,borderRadius:11,backgroundColor:'#e8f2f3',borderWidth:1,borderColor:'#d8e7e9',marginTop:6},featureTag:{fontSize:8,letterSpacing:1,color:'#286c8b',fontWeight:'800'},featureTitle:{fontSize:14,fontWeight:'700',color:'#192b3d',marginTop:7},featureCopy:{fontSize:10,lineHeight:15,color:'#637983',marginTop:4},input:{backgroundColor:'white',borderColor:'#dfe6e8',borderWidth:1,borderRadius:9,padding:13,fontSize:14,color:'#203744',marginTop:12},primary:{backgroundColor:'#286c8b',borderRadius:9,padding:14,alignItems:'center',marginTop:13,minHeight:47,justifyContent:'center'},primaryText:{color:'white',fontSize:13,fontWeight:'700'},back:{alignItems:'center',padding:16},backText:{color:'#286c8b',fontSize:12,fontWeight:'700'},error:{color:'#a44840',backgroundColor:'#fff1ef',padding:10,marginTop:10,borderRadius:7,fontSize:12},notice:{color:'#397658',backgroundColor:'#f0f8f3',padding:10,marginTop:10,borderRadius:7,fontSize:12,lineHeight:18}});
