import { useState } from 'react';
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { clearSharedPayloads, useIncomingShare } from 'expo-sharing';
import { apiFetch } from '../../../core/api/client';
import type { Scan } from '../../analysis/types/scan';


export default function HandleShareScreen() {
  const { resolvedSharedPayloads, sharedPayloads, isResolving, error } = useIncomingShare();
  const [text,setText]=useState(''); const [result,setResult]=useState<Scan|null>(null); const [busy,setBusy]=useState(false); const [failure,setFailure]=useState(''); const [needsSignIn,setNeedsSignIn]=useState(false);
  const image = resolvedSharedPayloads.find(item=>item.contentType==='image'&&'contentUri' in item&&!!item.contentUri);
  const previewText = sharedPayloads.map(item=>item.value).filter(Boolean).join('\n');
  const urlPayload = resolvedSharedPayloads.find(item=>item.contentType==='website'&&'contentUri' in item);
  const displayedText = text || urlPayload?.contentUri || previewText;

  async function analyzeShared() {
    setBusy(true);setFailure('');setResult(null);
    try {
      const response = image && 'contentUri' in image
        ? await apiFetch('/analyze/screenshot', {method:'POST',body:(()=>{const data=new FormData();data.append('file',{uri:image.contentUri,name:image.originalName??'shared-image.jpg',type:image.contentMimeType??'image/jpeg'} as unknown as Blob);return data;})()})
        : await apiFetch(/^https?:\/\/\S+$/i.test(displayedText.trim())?'/analyze/url':'/analyze/message',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:displayedText.trim()})});
      const body=await response.json();if(!response.ok){if(response.status===401||response.status===403)setNeedsSignIn(true);throw new Error(body?.error?.message||'Shared content analyze nahi ho saka.');}setNeedsSignIn(false);setResult(body.data as Scan);
    } catch(reason){setFailure(reason instanceof Error?reason.message:'Shared content check fail hui.')}finally{setBusy(false)}
  }

  function dismiss(){clearSharedPayloads();router.replace('/');}
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Pressable onPress={dismiss}><Text style={styles.back}>‹ Close shared item</Text></Pressable><Text style={styles.kicker}>SHARED TO PROOFLENS</Text><Text style={styles.title}>Check this before you trust it.</Text><Text style={styles.copy}>This content came from another app. ProofLens will inspect it only after you choose Analyze.</Text>{isResolving?<ActivityIndicator color="#286c8b"/>:null}{error&&<Text style={styles.error}>{error.message}</Text>}{image&&'contentUri' in image&&image.contentUri?<Image source={{uri:image.contentUri}} style={styles.preview}/>:null}<TextInput style={styles.input} multiline value={text||displayedText} onChangeText={setText} placeholder="Shared URL or message" autoCapitalize="none"/>{failure!==''&&<Text style={styles.error}>{failure}</Text>}{needsSignIn&&<Pressable style={styles.secondary} onPress={()=>router.replace('/?returnToShare=1')}><Text style={styles.secondaryText}>Sign in and keep this shared item</Text></Pressable>}{!result?<Pressable style={styles.primary} onPress={analyzeShared} disabled={busy||isResolving||(!displayedText&&!image)}>{busy?<ActivityIndicator color="white"/>:<Text style={styles.primaryText}>Analyze shared content</Text>}</Pressable>:<View style={styles.report}><Text style={[styles.title,levelStyle(result.risk_level)]}>{result.risk_level} RISK · {result.risk_score}/100</Text><Text style={styles.copy}>Confidence: {result.confidence}</Text><Text style={styles.reportTitle}>Assessment</Text><Text style={styles.copy}>{result.summary}</Text>{result.analysis_meta?.local_ai?.insight&&<View style={styles.evidence}><Text style={styles.reportTitle}>Local AI explanation · {result.analysis_meta.local_ai.model||'Ollama'}</Text><Text style={styles.copy}>{result.analysis_meta.local_ai.insight}</Text><Text style={styles.disclaimer}>Advisory only; this does not affect the evidence or risk score.</Text></View>}{result.evidence.map((item,index)=><View style={styles.evidence} key={`${item.title}-${index}`}><Text style={styles.reportTitle}>{item.title}</Text><Text style={styles.copy}>{item.description}</Text></View>)}<Text style={styles.reportTitle}>Recommended action</Text>{result.recommendations.map((item,index)=><Text style={styles.copy} key={index}>• {item}</Text>)}</View>}<Pressable style={styles.clear} onPress={dismiss}><Text style={styles.clearText}>Clear shared content</Text></Pressable></ScrollView>;
}
function levelStyle(level:string){return level==='LOW'?styles.low:level==='CAUTION'?styles.caution:styles.high;}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#f7f9fa'},content:{padding:22,paddingTop:55,paddingBottom:50},back:{fontSize:12,color:'#286c8b',fontWeight:'700',marginBottom:24},kicker:{fontSize:10,letterSpacing:1.3,color:'#8999a2',fontWeight:'700'},title:{fontSize:23,fontWeight:'700',color:'#192b3d',marginTop:8,marginBottom:9},copy:{fontSize:12,color:'#71828b',lineHeight:18,marginVertical:5},input:{backgroundColor:'white',borderColor:'#dfe6e8',borderWidth:1,borderRadius:9,padding:13,fontSize:13,color:'#203744',marginTop:13,minHeight:100,textAlignVertical:'top'},primary:{backgroundColor:'#286c8b',borderRadius:9,padding:14,alignItems:'center',marginTop:13,minHeight:47,justifyContent:'center'},primaryText:{color:'white',fontSize:13,fontWeight:'700'},secondary:{borderColor:'#286c8b',borderWidth:1,borderRadius:9,padding:14,alignItems:'center',marginTop:10,minHeight:47,justifyContent:'center'},secondaryText:{color:'#286c8b',fontSize:13,fontWeight:'700'},error:{color:'#a44840',backgroundColor:'#fff1ef',padding:10,marginTop:10,borderRadius:7,fontSize:12},preview:{width:'100%',height:220,resizeMode:'contain',backgroundColor:'#e9eff0',borderRadius:9,marginVertical:12},report:{backgroundColor:'white',borderWidth:1,borderColor:'#e7ecee',borderRadius:10,padding:15,marginTop:15},reportTitle:{fontSize:12,fontWeight:'700',color:'#344d59',marginTop:10},evidence:{borderTopWidth:1,borderColor:'#edf0f1',marginTop:12,paddingTop:8},disclaimer:{fontSize:10,color:'#87949b',lineHeight:15,marginTop:5},low:{color:'#438267'},caution:{color:'#987331'},high:{color:'#a24e44'},clear:{alignItems:'center',padding:15},clearText:{color:'#798a93',fontSize:11}});
